<?php
include_once 'lib/socketServer.php';
include_once 'lib/movistarGTISOPackager.php';
    $jack = new isoPack();
    $packResult = "";
    $jack->addMTI('0200');
    $jack->addData(2, '44384759');
    $jack->addData(3, '180000');
    $jack->addData(4, 100);
    $jack->addData(11, random_int(100000,999999));
    $jack->addData(12, date('His'));
    $jack->addData(13, date('md'));
    $jack->addData(24, '119');
    //$jack->addData(24, (int) substr($message,78,4));
    //$jack->addData(38, (string) rand(100000,99999));
    //$jack->addData(39, '00');
    $jack->addData(41, '1234567');
    $jack->addData(42, '123456789012345');    
    $data = $jack->getData();
    var_dump($jack->getBitmap());
    var_dump($data);
    echo "\n";
    $packResult .= pack('H*', $jack->getMTI());
    $packResult .= pack('H*', $jack->getBitmap());
    $packResult .= pack('H*', $data[2]);
    $packResult .= pack('H*', $data[3]);
    $packResult .= pack('H*', $data[4]);
    $packResult .= pack('H*', $data[11]);
    $packResult .= pack('H*', $data[12]);
    $packResult .= pack('H*', $data[13]);
    $packResult .= pack('n*', $data[24]);
    $packResult .= $data[41];
    $packResult .= $data[42];
    $packResult = pack('H*', "6000000003").$packResult;
    $isoLength = strlen($packResult);
    $packResult = pack('n*', $isoLength).$packResult;
    unset($jack);
    var_dump ($packResult);
    var_dump(unpack('H*', $packResult));
    echo "\n";
    $client = new socketProcessor('localhost', 9000, 'C');
    var_dump($client->sendMessage($packResult));
    unset($client);